# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-03-23 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(db_column='date', verbose_name='更新时间')),
                ('province', models.CharField(db_column='province', max_length=15, verbose_name='省')),
                ('city', models.CharField(db_column='city', max_length=15, verbose_name='市')),
                ('confirm', models.IntegerField(blank=True, db_column='confirm', null=True, verbose_name='累计确诊')),
                ('confirm_add', models.IntegerField(blank=True, db_column='confirm_add', null=True, verbose_name='新增确诊')),
                ('dead', models.IntegerField(blank=True, db_column='dead', null=True, verbose_name='累计死亡')),
                ('heal', models.IntegerField(blank=True, db_column='heal', null=True, verbose_name='累计治愈')),
            ],
            options={
                'verbose_name': '详细数据',
                'verbose_name_plural': '详细数据',
                'db_table': 'detail',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_column='date', verbose_name='日期')),
                ('confirm', models.IntegerField(blank=True, db_column='confirm', null=True, verbose_name='累计确诊')),
                ('confirm_add', models.IntegerField(blank=True, db_column='confirm_add', null=True, verbose_name='新增确诊')),
                ('suspect', models.IntegerField(blank=True, db_column='suspect', null=True, verbose_name='剩余疑似')),
                ('suspect_add', models.IntegerField(blank=True, db_column='suspect_add', null=True, verbose_name='新增疑似')),
                ('dead', models.IntegerField(blank=True, db_column='dead', null=True, verbose_name='累计死亡')),
                ('dead_add', models.IntegerField(blank=True, db_column='dead_add', null=True, verbose_name='新增死亡')),
                ('heal', models.IntegerField(blank=True, db_column='heal', null=True, verbose_name='累计治愈')),
                ('heal_add', models.IntegerField(blank=True, db_column='heal_add', null=True, verbose_name='新增治愈')),
            ],
            options={
                'verbose_name': '历史数据',
                'verbose_name_plural': '历史数据',
                'db_table': 'history',
            },
        ),
    ]
