# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-03-23 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='confirm_add',
        ),
        migrations.AddField(
            model_name='detail',
            name='nowConfirm',
            field=models.IntegerField(blank=True, db_column='nowConfirm', null=True, verbose_name='现有确诊'),
        ),
        migrations.AddField(
            model_name='detail',
            name='suspect',
            field=models.IntegerField(blank=True, db_column='suspect', null=True, verbose_name='新增确诊'),
        ),
    ]
