# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-03-29 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200323_2352'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(db_column='date', verbose_name='更新时间')),
                ('name', models.CharField(db_column='name', max_length=30, verbose_name='热搜内容')),
                ('value', models.IntegerField(db_column='value', verbose_name='热搜指数')),
            ],
            options={
                'verbose_name': '热搜数据',
                'verbose_name_plural': '热搜数据',
                'db_table': 'hotsearch',
            },
        ),
    ]
